version: '2.1'

services:
  build-env:
    build:
      context: .
      dockerfile: Dockerfile.service-builder
    image: envoy-service-builder

  service-a:
    build:
      context: service-a
    ports:
      - "8080:8080"
      - "9090:9090"
      - "8001:8001"
    expose:
      - "8080"
      - "9090"
    depends_on:
      - build-env
    networks:
      envoymesh:
        aliases:
          - service-a

  service-b:
    build:
      context: service-b
    ports:
      - "8081:8080"
      - "9090:9090"
    expose:
      - "8080"
      - "9090"
    depends_on:
      - build-env
    networks:
      envoymesh:
        aliases:
          - service-b

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    expose:
      - "9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      envoymesh:
        aliases:
          - zipkin

networks:
  envoymesh: {}