version: '2.1'

services:
  build-env:
    build:
      context: .
      dockerfile: Dockerfile.service-builder
    image: envoy-service-builder

  service-a:
    build:
      context: service-a
    ports:
      - "8080:8080"
      - "9090:9090"
    expose:
      - "9090"
    depends_on:
      - build-env
    networks:
      envoymesh:
        aliases:
          - service-a

  service-b:
    build:
      context: service-b
    expose:
      - "9090"
    depends_on:
      - build-env
    networks:
      envoymesh:
        aliases:
          - service-b

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    expose:
      - "9411"
    environment:
      - STORAGE_TYPE=mem
    networks:
      envoymesh:
        aliases:
          - zipkin

  statsd:
    image: prom/statsd-exporter:latest
    ports:
    - "9125:9125"
    - "9102:9102"
    networks:
      envoymesh:
        aliases:
          - statsd

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus-conf.yaml:/etc/prometheus.yaml
    ports:
    - "19090:9090"
    expose:
    - "9090"
    command: "--config.file=/etc/prometheus.yaml"
    networks:
      envoymesh:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    ports:
    - "3000:3000"
    networks:
      envoymesh:
        aliases:
          - grafana

networks:
  envoymesh: {}